# Generated by Django 3.1.1 on 2020-09-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='active_listing',
            field=models.BooleanField(default=True),
        ),
    ]
