# Generated by Django 3.1.1 on 2020-10-23 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedopt', '0003_auto_20201023_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedopt.pet'),
        ),
    ]
