# Generated by Django 3.1.1 on 2020-10-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedopt', '0002_auto_20201024_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='adopted_by',
        ),
    ]
